services:
  server:
    image: ${PROJECT_NAME}-app
    container_name: ${PROJECT_NAME}-server
    user: ${CURRENT_UID}:${CURRENT_GID}
    working_dir: /app
    volumes:
      - ../:/app
    environment:
      - ADDRESS=${SRV_LISTEN}
      - DATABASE_DSN=${DATABASE_DSN}
    ports:
      - "${LOCAL_PORT}:${SRV_PORT}"
    command: /app/cmd/server/server
    networks:
      - metrics-collector
  agent:
    image: ${PROJECT_NAME}-app
    container_name: ${PROJECT_NAME}-agent
    user: ${CURRENT_UID}:${CURRENT_GID}
    working_dir: /app
    volumes:
      - ../:/app
    environment:
      - ADDRESS=${SRV_ADDR}
    command: /app/cmd/agent/agent
    networks:
      - metrics-collector
  postgres:
    image: postgres:latest
    container_name: ${PROJECT_NAME}-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: praktikum
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - ../pgdata:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
networks:
  metrics-collector:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.22.0.0/16