// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.2
// source: contracts/metric.proto

package contracts

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metrics struct {
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
	Delta         int64   `protobuf:"varint,1,opt,name=delta,proto3" json:"delta,omitempty"`
	Value         float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_contracts_metric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_metric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_contracts_metric_proto_rawDescGZIP(), []int{0}
}

func (x *Metrics) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *Metrics) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metrics) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metrics) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_contracts_metric_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_metric_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_contracts_metric_proto_rawDescGZIP(), []int{1}
}

func (x *GetMetricsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMetricsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *Metrics               `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_contracts_metric_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_metric_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_contracts_metric_proto_rawDescGZIP(), []int{2}
}

func (x *GetMetricsResponse) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type UpdateMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *Metrics               `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricsRequest) Reset() {
	*x = UpdateMetricsRequest{}
	mi := &file_contracts_metric_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricsRequest) ProtoMessage() {}

func (x *UpdateMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_metric_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricsRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetricsRequest) Descriptor() ([]byte, []int) {
	return file_contracts_metric_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMetricsRequest) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type BatchUpdateMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metrics             `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpdateMetricsRequest) Reset() {
	*x = BatchUpdateMetricsRequest{}
	mi := &file_contracts_metric_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpdateMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateMetricsRequest) ProtoMessage() {}

func (x *BatchUpdateMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_metric_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateMetricsRequest.ProtoReflect.Descriptor instead.
func (*BatchUpdateMetricsRequest) Descriptor() ([]byte, []int) {
	return file_contracts_metric_proto_rawDescGZIP(), []int{4}
}

func (x *BatchUpdateMetricsRequest) GetMetrics() []*Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_contracts_metric_proto protoreflect.FileDescriptor

const file_contracts_metric_proto_rawDesc = "" +
	"\n" +
	"\x16contracts/metric.proto\x12\x06metric\x1a\x1bgoogle/protobuf/empty.proto\"Y\n" +
	"\aMetrics\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\x03R\x05delta\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"7\n" +
	"\x11GetMetricsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"?\n" +
	"\x12GetMetricsResponse\x12)\n" +
	"\ametrics\x18\x01 \x01(\v2\x0f.metric.MetricsR\ametrics\"A\n" +
	"\x14UpdateMetricsRequest\x12)\n" +
	"\ametrics\x18\x01 \x01(\v2\x0f.metric.MetricsR\ametrics\"F\n" +
	"\x19BatchUpdateMetricsRequest\x12)\n" +
	"\ametrics\x18\x01 \x03(\v2\x0f.metric.MetricsR\ametrics2\xf3\x01\n" +
	"\x0eMetricsService\x12E\n" +
	"\n" +
	"GetMetrics\x12\x19.metric.GetMetricsRequest\x1a\x1a.metric.GetMetricsResponse\"\x00\x12G\n" +
	"\rUpdateMetrics\x12\x1c.metric.UpdateMetricsRequest\x1a\x16.google.protobuf.Empty\"\x00\x12Q\n" +
	"\x12BatchUpdateMetrics\x12!.metric.BatchUpdateMetricsRequest\x1a\x16.google.protobuf.Empty\"\x00B\x14Z\x12internal/contractsb\x06proto3"

var (
	file_contracts_metric_proto_rawDescOnce sync.Once
	file_contracts_metric_proto_rawDescData []byte
)

func file_contracts_metric_proto_rawDescGZIP() []byte {
	file_contracts_metric_proto_rawDescOnce.Do(func() {
		file_contracts_metric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_metric_proto_rawDesc), len(file_contracts_metric_proto_rawDesc)))
	})
	return file_contracts_metric_proto_rawDescData
}

var file_contracts_metric_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_contracts_metric_proto_goTypes = []any{
	(*Metrics)(nil),                   // 0: metric.Metrics
	(*GetMetricsRequest)(nil),         // 1: metric.GetMetricsRequest
	(*GetMetricsResponse)(nil),        // 2: metric.GetMetricsResponse
	(*UpdateMetricsRequest)(nil),      // 3: metric.UpdateMetricsRequest
	(*BatchUpdateMetricsRequest)(nil), // 4: metric.BatchUpdateMetricsRequest
	(*emptypb.Empty)(nil),             // 5: google.protobuf.Empty
}
var file_contracts_metric_proto_depIdxs = []int32{
	0, // 0: metric.GetMetricsResponse.metrics:type_name -> metric.Metrics
	0, // 1: metric.UpdateMetricsRequest.metrics:type_name -> metric.Metrics
	0, // 2: metric.BatchUpdateMetricsRequest.metrics:type_name -> metric.Metrics
	1, // 3: metric.MetricsService.GetMetrics:input_type -> metric.GetMetricsRequest
	3, // 4: metric.MetricsService.UpdateMetrics:input_type -> metric.UpdateMetricsRequest
	4, // 5: metric.MetricsService.BatchUpdateMetrics:input_type -> metric.BatchUpdateMetricsRequest
	2, // 6: metric.MetricsService.GetMetrics:output_type -> metric.GetMetricsResponse
	5, // 7: metric.MetricsService.UpdateMetrics:output_type -> google.protobuf.Empty
	5, // 8: metric.MetricsService.BatchUpdateMetrics:output_type -> google.protobuf.Empty
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_contracts_metric_proto_init() }
func file_contracts_metric_proto_init() {
	if File_contracts_metric_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_metric_proto_rawDesc), len(file_contracts_metric_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_metric_proto_goTypes,
		DependencyIndexes: file_contracts_metric_proto_depIdxs,
		MessageInfos:      file_contracts_metric_proto_msgTypes,
	}.Build()
	File_contracts_metric_proto = out.File
	file_contracts_metric_proto_goTypes = nil
	file_contracts_metric_proto_depIdxs = nil
}
