name: go vet test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  multichecker:
    runs-on: ubuntu-latest
    container: golang:1.24
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download multichecker binary
        uses: robinraju/release-downloader@v1.8
        with:
          repository: ktigay/multichecker
          latest: true
          fileName: multichecker
          out-file-path: .tools
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup multichecker binary
        run: |
          chmod -R +x $GITHUB_WORKSPACE/.tools/multichecker
          mv $GITHUB_WORKSPACE/.tools/multichecker /usr/local/bin/multichecker

      - name: Run multichecker
        run: |
          go vet -vettool=$(which multichecker) ./...
